# Numpy

In [2]:
import numpy as np
a=np.array([1, 2, 3])
a

array([1, 2, 3])

**shape**
شکل مربوط به آرایه

In [3]:
a.shape

(3,)

**ndim**
بعد آرایه

In [4]:
a.ndim

1

**dtype** نوع داده های آرایه

In [5]:
a.dtype

dtype('int32')

**size**
تعداد عناصر 

In [6]:
a.size

3

In [7]:
b=np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape


(2, 3)

In [9]:
b.ndim

2

In [10]:
b.dtype

dtype('int32')

In [11]:
b.size

6

In [21]:
c=np.array([[1, 2.6, 3],[4, 5j, 6]])

In [22]:
c.shape

(2, 3)

In [23]:
c.dtype

dtype('complex128')

In [24]:
c

array([[1. +0.j, 2.6+0.j, 3. +0.j],
       [4. +0.j, 0. +5.j, 6. +0.j]])

**Arange** چیزی شبیه رنج در پایتون

In [26]:
d = np.arange(1,20)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
d.size

19

In [28]:
d[-1]

19

In [29]:
d[1]

2

**linspace** در رنجی مشخص اعدادی با فاصلله برابر را بر میگرداند ---->retstep=true

In [39]:
e = np.linspace(1,19,num=9, retstep=True)
e

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  , 12.25, 14.5 , 16.75, 19.  ]), 2.25)

In [41]:
d.dtype

dtype('int32')

**ones**

In [46]:
f=np.ones((2,5))
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**zeros**

In [45]:
g=np.zeros((2,5),dtype=int)
g

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**Random**

In [56]:
h=np.random.randint(1, 48, size=10)
h

array([ 2, 13,  8, 46,  7, 26, 21, 38, 19, 21])

**seed**

In [55]:
np.random.seed(1)
p=np.random.randint(1, 48, size=10)
p

array([38, 44, 13,  9, 10, 12,  6, 16,  1, 17])

In [74]:
k = np.arange(1,25)
k.shape=(6,4)
k

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [76]:
k[-1]

array([21, 22, 23, 24])

In [79]:
k[-1,-4]

21

In [80]:
k[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [94]:
o=np.random.randint(1, 9, size=(2, 3, 4))
o

array([[[1, 8, 8, 2],
        [2, 6, 4, 1],
        [1, 6, 6, 7]],

       [[5, 6, 7, 3],
        [5, 4, 6, 4],
        [8, 6, 1, 4]]])

In [95]:
o[0][0][0]

1

In [98]:
o[:, :, :2]

array([[[1, 8],
        [2, 6],
        [1, 6]],

       [[5, 6],
        [5, 4],
        [8, 6]]])

In [113]:
np.random.seed(1)
q=np.random.randint(0, 100, size=60)
q

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1, 76, 71,  6, 25, 50, 20, 18,
       84, 11, 28, 29, 14, 50, 68, 87, 87, 94, 96, 86, 13,  9,  7, 63, 61,
       22, 57,  1,  0, 60, 81,  8, 88, 13, 47, 72, 30, 71,  3, 70, 21, 49,
       57,  3, 68, 24, 43, 76, 26, 52, 80])

In [114]:
q.ndim

1

In [115]:
q.shape

(60,)

In [116]:
q=q.reshape(1,60)
q.shape

(1, 60)

In [117]:
q=q.reshape((4,3,5))
q

array([[[37, 12, 72,  9, 75],
        [ 5, 79, 64, 16,  1],
        [76, 71,  6, 25, 50]],

       [[20, 18, 84, 11, 28],
        [29, 14, 50, 68, 87],
        [87, 94, 96, 86, 13]],

       [[ 9,  7, 63, 61, 22],
        [57,  1,  0, 60, 81],
        [ 8, 88, 13, 47, 72]],

       [[30, 71,  3, 70, 21],
        [49, 57,  3, 68, 24],
        [43, 76, 26, 52, 80]]])

In [118]:
unique_q = np.unique(q)
unique_q

array([ 0,  1,  3,  5,  6,  7,  8,  9, 11, 12, 13, 14, 16, 18, 20, 21, 22,
       24, 25, 26, 28, 29, 30, 37, 43, 47, 49, 50, 52, 57, 60, 61, 63, 64,
       68, 70, 71, 72, 75, 76, 79, 80, 81, 84, 86, 87, 88, 94, 96])

In [119]:
q[q>10]

array([37, 12, 72, 75, 79, 64, 16, 76, 71, 25, 50, 20, 18, 84, 11, 28, 29,
       14, 50, 68, 87, 87, 94, 96, 86, 13, 63, 61, 22, 57, 60, 81, 88, 13,
       47, 72, 30, 71, 70, 21, 49, 57, 68, 24, 43, 76, 26, 52, 80])

In [120]:
shart1 = q>10
shart1

array([[[ True,  True,  True, False,  True],
        [False,  True,  True,  True, False],
        [ True,  True, False,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[False, False,  True,  True,  True],
        [ True, False, False,  True,  True],
        [False,  True,  True,  True,  True]],

       [[ True,  True, False,  True,  True],
        [ True,  True, False,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [121]:
shart2= q % 2 ==0
shart2

array([[[False,  True,  True, False, False],
        [False, False,  True,  True, False],
        [ True, False,  True, False,  True]],

       [[ True,  True,  True, False,  True],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False]],

       [[False, False, False, False,  True],
        [False, False,  True,  True, False],
        [ True,  True, False, False,  True]],

       [[ True, False, False,  True, False],
        [False, False, False,  True,  True],
        [False,  True,  True,  True,  True]]])

In [122]:
mask=np.logical_and(shart1, shart2)
q[mask]

array([12, 72, 64, 16, 76, 50, 20, 18, 84, 28, 14, 50, 68, 94, 96, 86, 22,
       60, 88, 72, 30, 70, 68, 24, 76, 26, 52, 80])

In [123]:
mask2=np.logical_or(shart1, shart2)
q[mask2]

array([37, 12, 72, 75, 79, 64, 16, 76, 71,  6, 25, 50, 20, 18, 84, 11, 28,
       29, 14, 50, 68, 87, 87, 94, 96, 86, 13, 63, 61, 22, 57,  0, 60, 81,
        8, 88, 13, 47, 72, 30, 71, 70, 21, 49, 57, 68, 24, 43, 76, 26, 52,
       80])

In [124]:
z= np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
z+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [133]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
y=np.random.randint(1, 9, size=10).reshape(1, 10)
y

array([[3, 3, 8, 8, 8, 8, 2, 8, 4, 5]])

In [135]:
z + y

array([[ 3,  4, 10, 11, 12, 13,  8, 15, 12, 14]])

In [136]:
z - y

array([[-3, -2, -6, -5, -4, -3,  4, -1,  4,  4]])

In [137]:
z * y

array([[ 0,  3, 16, 24, 32, 40, 12, 56, 32, 45]])

In [139]:
u= np.arange(5)
u

array([0, 1, 2, 3, 4])

In [143]:
v=np.random.randint(1 , 9, size=50).reshape(10, 5)
v

array([[2, 6, 8, 1, 2],
       [4, 2, 2, 7, 6],
       [5, 5, 4, 7, 6],
       [1, 4, 8, 1, 4],
       [2, 3, 8, 6, 6],
       [5, 6, 1, 6, 1],
       [6, 4, 2, 2, 8],
       [6, 1, 7, 6, 8],
       [1, 5, 3, 6, 4],
       [5, 3, 7, 7, 1]])

In [144]:
u + v

array([[ 2,  7, 10,  4,  6],
       [ 4,  3,  4, 10, 10],
       [ 5,  6,  6, 10, 10],
       [ 1,  5, 10,  4,  8],
       [ 2,  4, 10,  9, 10],
       [ 5,  7,  3,  9,  5],
       [ 6,  5,  4,  5, 12],
       [ 6,  2,  9,  9, 12],
       [ 1,  6,  5,  9,  8],
       [ 5,  4,  9, 10,  5]])

In [145]:
n=np.arange(5).reshape(5, 1)
n

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [147]:
u * n

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [148]:
u.dot(n)

array([30])

In [149]:
v

array([[2, 6, 8, 1, 2],
       [4, 2, 2, 7, 6],
       [5, 5, 4, 7, 6],
       [1, 4, 8, 1, 4],
       [2, 3, 8, 6, 6],
       [5, 6, 1, 6, 1],
       [6, 4, 2, 2, 8],
       [6, 1, 7, 6, 8],
       [1, 5, 3, 6, 4],
       [5, 3, 7, 7, 1]])

In [150]:
np.sum(v)/v.size

4.42

In [151]:
np.mean(v)

4.42

In [152]:
np.max(v)

8

In [153]:
np.var(v)

5.3636

In [154]:
np.std(v)

2.3159447316376096

In [158]:
np.sqrt(np.var(v))

2.3159447316376096

In [159]:
names=["hadi","amir","zahra","ali"]
ages=[20, 15, 25, 28]
shahrha=["ahvaz","esfahan","tehran","mashhad"]

In [188]:
Olgo=[("name", "U1"),("age", "i4"),("shahr","U15")]

In [189]:
Hadi_Array=np.zeros((5), dtype=Olgo)
Hadi_Array

array([('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
      dtype=[('name', '<U1'), ('age', '<i4'), ('shahr', '<U15')])

In [190]:
Hadi_Array[1]=("Hadi", 20, "ahvaz")
Hadi_Array

array([('',  0, ''), ('H', 20, 'ahvaz'), ('',  0, ''), ('',  0, ''),
       ('',  0, '')],
      dtype=[('name', '<U1'), ('age', '<i4'), ('shahr', '<U15')])

In [191]:
Hadi_Array[3]=("Ali", 30, "bushehr")
Hadi_Array

array([('',  0, ''), ('H', 20, 'ahvaz'), ('',  0, ''),
       ('A', 30, 'bushehr'), ('',  0, '')],
      dtype=[('name', '<U1'), ('age', '<i4'), ('shahr', '<U15')])

In [192]:
Hadi_Array["age"]

array([ 0, 20,  0, 30,  0])

In [193]:
Hadi_Array["name"]

array(['', 'H', '', 'A', ''], dtype='<U1')