In [28]:
from matplotlib.image import imread
import numpy as np
import datetime
import pandas as pd

<img src="images.jpg" width=250 height=100 />

In [26]:
image1 = imread("images.jpg")

In [3]:
type(image1)

numpy.ndarray

In [4]:
image1.size

150975

In [5]:
image1.shape

(183, 275, 3)

In [6]:
image1.ndim

3

In [7]:
image1[182]

array([[ 29,  63,   2],
       [ 40,  55,   0],
       [ 59,  65,  17],
       [ 54,  78,  26],
       [ 65, 105,  52],
       [ 49,  81,  34],
       [  0,  11,   0],
       [  0,  16,   0],
       [  0,  44,   1],
       [  4,  65,  21],
       [  4,  52,  14],
       [ 58, 102,  66],
       [ 83, 148, 105],
       [ 45, 133,  82],
       [ 47, 131,  81],
       [ 23,  88,  45],
       [ 31,  34,  17],
       [ 69,  70,  56],
       [ 68,  65,  56],
       [ 37,  34,  27],
       [ 40,  43,  34],
       [ 21,  35,  20],
       [ 13,  43,  15],
       [ 34,  81,  39],
       [ 32,  95,  38],
       [ 23,  94,  26],
       [ 42, 112,  40],
       [ 53, 112,  44],
       [ 65, 105,  45],
       [ 58,  76,  28],
       [ 69,  67,  29],
       [ 20,   7,   0],
       [  0,  37,   8],
       [  1,  34,   7],
       [  0,  26,   1],
       [ 19,  36,  17],
       [  2,  11,   0],
       [  4,  11,   0],
       [ 17,  26,   9],
       [  5,  20,   1],
       [  0,  17,   0],
       [  0,  14

In [8]:
image2 = imread("Black-windows-542931.jpg")

In [9]:
image2.size, image2.shape, image2.ndim

(6912000, (1200, 1920, 3), 3)

In [10]:
image2[1199, 1900]

array([2, 0, 1], dtype=uint8)

In [22]:
a = np.random.randint(10, 99, size=250000, dtype=np.int64)
b = np.random.randint(10, 99, size=250000, dtype=np.int64)

In [23]:
numpy1 = datetime.datetime.now()
r_numpy = np.dot(a, b)
numpy2= datetime.datetime.now()
time_numpy = numpy2-numpy1
r_numpy, time_numpy

(728161362, datetime.timedelta(microseconds=998))

In [24]:
python1 = datetime.datetime.now()
r_python = 0
for i,j in zip(a,b):
    r_python += i*j
python2= datetime.datetime.now()
time_python = python2-python1
r_numpy, time_python

(728161362, datetime.timedelta(microseconds=146906))

In [25]:
time_python/ time_numpy

147.2004008016032

In [32]:
numberOFsale= np.random.randint(5,10 ,size=(7 , 3))
numberOFsale

array([[7, 6, 5],
       [7, 9, 6],
       [7, 5, 8],
       [5, 9, 6],
       [7, 6, 5],
       [5, 8, 5],
       [7, 5, 5]])

In [35]:
Sales=pd.DataFrame(numberOFsale, index=["Satureday", "Sunday", "Monday", "Thuseday","Wednesday","Thursday","Friday"], columns=["shalvar", "Shirt","T_shirt"])
Sales

shalvar  Shirt  T_shirt
Satureday        7      6        5
Sunday           7      9        6
Monday           7      5        8
Thuseday         5      9        6
Wednesday        7      6        5
Thursday         5      8        5
Friday           7      5        5

In [45]:
Price = np.array([150, 300, 90])
Price.shape=(1, 3)
Price

array([[150, 300,  90]])

In [43]:
Cloth_Price = pd.DataFrame(Price, index=["Price"], columns=["shalvar", "Shirt","T_shirt"])
Cloth_Price

shalvar  Shirt  T_shirt
Price      150    300       90

In [44]:
Price.shape

(1, 3)

In [46]:
Sales=pd.DataFrame(numberOFsale, index=["Satureday", "Sunday", "Monday", "Thuseday","Wednesday","Thursday","Friday"], columns=["shalvar", "Shirt","T_shirt"])
Sales

shalvar  Shirt  T_shirt
Satureday        7      6        5
Sunday           7      9        6
Monday           7      5        8
Thuseday         5      9        6
Wednesday        7      6        5
Thursday         5      8        5
Friday           7      5        5

In [47]:
Cloth_Price = pd.DataFrame(Price, index=["Price"], columns=["shalvar", "Shirt","T_shirt"])
Cloth_Price

shalvar  Shirt  T_shirt
Price      150    300       90

In [50]:
Advantage = Cloth_Price.dot(Sales.T)
Advantage

Satureday  Sunday  Monday  Thuseday  Wednesday  Thursday  Friday
Price       3300    4290    3270      3990       3300      3600    3000

In [53]:
Sales["Total Advantage"] = Advantage.T
Sales

shalvar  Shirt  T_shirt  Total Advantage
Satureday        7      6        5             3300
Sunday           7      9        6             4290
Monday           7      5        8             3270
Thuseday         5      9        6             3990
Wednesday        7      6        5             3300
Thursday         5      8        5             3600
Friday           7      5        5             3000

In [57]:
c1 = np.arange(1, 25).reshape(2, 3, 4)
c1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [58]:
c2 = c1
c2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [59]:
c2 == c1

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [60]:
c2 is c1

True

In [61]:
id(c2), id(c1)

(1815936245264, 1815936245264)

In [65]:
c1[1, 0, 0] = 999
c1

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [66]:
c2

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [67]:
#shadow_copy
c3 = c1.view()
c3

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [68]:
c1[0, 0, 0] = 999
c1

array([[[999,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [69]:
c3

array([[[999,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [70]:
c3 == c1

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [71]:
c3 is c1

False

In [72]:
id(c1), id(c3)

(1815936245264, 1815936131792)

In [73]:
#Deep_copy
c4 = np.copy(c1)
c4

array([[[999,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [74]:
c4 == c1

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [75]:
c4 is c1

False

In [77]:
c4[0, 0, 1] = 999
c4

array([[[999, 999,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [78]:
c1

array([[[999,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [79]:
c3[0, 0, 1]=999
c3

array([[[999, 999,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [80]:
c1

array([[[999, 999,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[999,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [81]:
d = np.arange(24)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
d.shape=(2, 3, 4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [83]:
d_reshape= d.reshape((2, 12))
d_reshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [84]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
d_reshape[0, 0] = 999
d_reshape

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [87]:
d

array([[[999,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [88]:
d is d_reshape

False

In [89]:
#flatten
#ravel

In [90]:
f = np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
g = np.append(f, [10, 11])
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
h = np.random.randint(1, 99, size=24).reshape(2, 3, 4)
h

array([[[62, 19, 91, 36],
        [61, 81, 87, 28],
        [28,  7, 81, 45]],

       [[45, 10, 86, 73],
        [28, 54, 57, 33],
        [88, 18, 22, 72]]])

In [94]:
k = np.random.randint(1, 99, size=24).reshape(2, 3, 4)
k

array([[[53, 95, 75,  1],
        [ 5, 26, 84, 82],
        [57, 11, 33, 92]],

       [[11, 67, 88, 98],
        [93, 50, 45, 39],
        [33, 21, 91, 28]]])

In [103]:
hk = np.append(h, k)
hk

array([62, 19, 91, 36, 61, 81, 87, 28, 28,  7, 81, 45, 45, 10, 86, 73, 28,
       54, 57, 33, 88, 18, 22, 72, 53, 95, 75,  1,  5, 26, 84, 82, 57, 11,
       33, 92, 11, 67, 88, 98, 93, 50, 45, 39, 33, 21, 91, 28])

In [109]:
hk0 = np.append(h, k, axis=0)
hk0

array([[[62, 19, 91, 36],
        [61, 81, 87, 28],
        [28,  7, 81, 45]],

       [[45, 10, 86, 73],
        [28, 54, 57, 33],
        [88, 18, 22, 72]],

       [[53, 95, 75,  1],
        [ 5, 26, 84, 82],
        [57, 11, 33, 92]],

       [[11, 67, 88, 98],
        [93, 50, 45, 39],
        [33, 21, 91, 28]]])

In [108]:
hk0.shape

(4, 3, 4)

In [107]:
hk1 = np.append(h, k, axis=1)
hk1

array([[[62, 19, 91, 36],
        [61, 81, 87, 28],
        [28,  7, 81, 45],
        [53, 95, 75,  1],
        [ 5, 26, 84, 82],
        [57, 11, 33, 92]],

       [[45, 10, 86, 73],
        [28, 54, 57, 33],
        [88, 18, 22, 72],
        [11, 67, 88, 98],
        [93, 50, 45, 39],
        [33, 21, 91, 28]]])

In [106]:
hk1.shape

(2, 6, 4)

In [101]:
hk2 = np.append(h, k, axis=2)
hk2

array([[[62, 19, 91, 36, 53, 95, 75,  1],
        [61, 81, 87, 28,  5, 26, 84, 82],
        [28,  7, 81, 45, 57, 11, 33, 92]],

       [[45, 10, 86, 73, 11, 67, 88, 98],
        [28, 54, 57, 33, 93, 50, 45, 39],
        [88, 18, 22, 72, 33, 21, 91, 28]]])

In [110]:
hk2.shape

(2, 3, 8)

In [111]:
h

array([[[62, 19, 91, 36],
        [61, 81, 87, 28],
        [28,  7, 81, 45]],

       [[45, 10, 86, 73],
        [28, 54, 57, 33],
        [88, 18, 22, 72]]])

In [119]:
k

array([[[53, 95, 75,  1],
        [ 5, 26, 84, 82],
        [57, 11, 33, 92]],

       [[11, 67, 88, 98],
        [93, 50, 45, 39],
        [33, 21, 91, 28]]])

In [113]:
#insert
#copyto
#empty
#POOOOOOOOOOOOOOOOOOOr karbord ****concatenate****

In [120]:
j1 = np.delete(k, 0, axis=2)
j1

array([[[95, 75,  1],
        [26, 84, 82],
        [11, 33, 92]],

       [[67, 88, 98],
        [50, 45, 39],
        [21, 91, 28]]])